### PR TITLE
Force update to Node 12

### PR DESCRIPTION
**Pull request by PathToLife**
Hi there,

I'm hoping to use your package in the latest stable version of react so I modified it a bit / cleaned the tests.

I wanted to use it with a node 12.X frontend that has these:
```
"dependencies": {
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@types/react-resize-detector": "^4.2.0",
    "@types/socket.io-client": "^1.4.32",
    "react": "^16.13.1",
    "typescript": "~3.7.2"
  }
```

This is a breaking change that will deprecate support for node 4, 5, 6
(all builds failed due to mocha support problems)

https://travis-ci.com/github/PathToLife/node-chess

I wouldn't merge it just yet, haven't integrated with the app fully, but I'll put it here for anyone wanting to use node 12 =)

### CODE REVIEW

**Comment by Seikho** [comment]
Thanks for the PR! I'll merge this in with a some other changes over the next couple of days.

**Comment by PathToLife** [comment]
Heya, all good, I've got a huge amount of type changes incoming.
Thanks for the project! ;)

**Comment by PathToLife** [comment]
all done :) 

Might i say neutrally that calculateMovePiece() (previously inside movePiece) - this is a whammy hahaha

didn't know that the history needed to be set before postAction for the pieces

**Comment by PathToLife** [comment]
https://travis-ci.com/github/PathToLife/node-chess/builds/162861776

**Comment by PathToLife** [comment]
Summary:

- Enable strict type checking and fix all type errors
This allows for a better understanding of what's going on
- Made an attempt at cleaning movePiece() function, tests passed after doing so. But requires a peer review
- Various Types added into types.d.ts, some // TODO directives related to typing done
- Removed 'var' and introduced const / let where appropriate
- Added boardToString function for debugging help
- Refactored Piece into IPiece & BoardPiece, a little easier to type initial piece definitions that way without having to check undefined in core board logic.

**Comment by PathToLife** [comment]
I'm looking for an js/ts chess variant analysis engine (bot game) without the GPL license (can't infect, need LGPL).

So far haven't found anything apart from Fairy-Stockfish-JS, Garbochess-JS modification is the next best bet.. I'm not that familiar with engines though.

**Comment by Seikho** [comment]
This was originally designed to be a sort-of isomorphic and declarative variant chess engine.
It shouldn't negatively interact with any of the dependencies you mentioned earlier. 

This is quite a significant amount of changes. I haven't touched this code base in quite a long time so it may take quite a while to review.

The tests I have aren't very exhaustive.
I'll investigate what needs to change in order to upgrad to TS 3.8, but I'm not too keen on significant refactoring at the same time.

**Comment by PathToLife** [comment]
Hi thanks for the reply,

I needed a great codebase to base the client / server on and wasn't confident without strict type checking hence the extensive changes.

Yeah understand being wary of this PR as well. Totally understand if we want to close it.

Would you prefer a lighter PR of what was done before? Before strict type checking?

**Comment by PathToLife** [comment]
Hi, there were a few issues when I tried using this pr in a react project.

Ended up continuing with development on the fork and fixing it (redid the npm build process).

Learned quite a lot due to your project =) Thank you

**Pull request closed without merging**
